### ISSUE TITLE
Support for custom stores

### ISSUE THREAD

**Issue by SecUpwN** [javiersantos/AppUpdater#1]
Good evening @javiersantos, thanks for publishing your great `AppUpdater` on GitHub! Do you think you could add support for custom stores? To be more specific, I would like to see support for checking for updates from [F-Droid](https://f-droid.org/) and [Aptoide](http://www.aptoide.com/). But since F-Droid builds apps from source when the codebase changes on GitHub or other places, I am not sure your `AppUpdater` can detect the correct way where to update from. Example: A user installs our app [AIMSICD](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) from GitHub releases and then your library notices that an update is available on Aptoide (published by ourselves) and F-Droid (automatically generated from source). How would the `AppUpdater` know which correct store to update our app from?

**Comment by javiersantos** [comment]
Hey @SecUpwN. The library will support F-Droid and Aptoide stores in upcoming updates! :+1: 

About your other question. The developer must provide the source where the latest updates are found, so you could provide the GitHub source for the apk that is located there and the F-Droid source for the other one (maybe using a different `buildTypes` or another workaround to detect that you are using the F-Droid version instead the other one).

```Java
.setUpdateFrom(UpdateFrom.GOOGLE_PLAY);
.setUpdateFrom(UpdateFrom.GITHUB);
.setUpdateFrom(UpdateFrom.AMAZON);
...
```

**Comment by krt16s** [comment]
Also it would be nice if we could use an arbitrary URL to a "latest" apk file that gets checked. That would ease up checking for Firefox updates without any stores available, like with https://github.com/krt16s/ffupdater

**Comment by javiersantos** [comment]
I hope the update v2.0 is useful for you two! The latest AppUpdater update supports a custom XML file for updates, without checking an store. #21

https://github.com/javiersantos/AppUpdater/releases/tag/2.0.1
