### ISSUE TITLE
Changing color of Title and Content?

### ISSUE THREAD

**Issue by SeefriedNoah** [javiersantos/AppUpdater#113]
Is it possible to change the color of the text?

`
.setTitleOnUpdateAvailable("Update available")
.setContentOnUpdateAvailable("Check out the latest version available of my app!")`

How can I change the color of, for example, these two texts?

**Comment by javiersantos** [comment]
It's not supported by the library. You should create a custom dialog by using `AppUpdaterUtils` instead.
