### ISSUE TITLE
how can i check if update is available or not on playstore while i launch app? i have to check update is available or not while i launch app every time? 

### ISSUE THREAD

**Issue by kushanshah11** [javiersantos/AppUpdater#114]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [ ] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
###### Builder
```Java
new AppUpdater(this)
   ...
   .start();
```

###### Reproduction Steps

1.
2.
3.

**Comment by kushanshah11** [comment]
is there any flag or something that i get when update available on playstore? if update is available i have to stop user on update screen only.  for which i have checked your code  

 new AppUpdater(context)
                        .setUpdateFrom(UpdateFrom.GOOGLE_PLAY)
                        .setDisplay(Display.DIALOG)
                        .showAppUpdated(false)
                        .setButtonDoNotShowAgain(null)
                        .setButtonDismiss(null)
                        .setCancelable(false)
                        .start();

and its working as per my requirements.

and yes i have confusion have to provide any GITHUB Link of apk ?

**Comment by beeret** [comment]
V

**Comment by javiersantos** [comment]
I'm not sure what your question is. If you want to know if there is a new update or not, you can use a custom callback: https://github.com/javiersantos/AppUpdater#using-custom-callbacks
