### ISSUE TITLE
force update???

### ISSUE THREAD

**Issue by mouness2020** [javiersantos/AppUpdater#115]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [ ] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
###### Builder
```Java
new AppUpdater(this)
   ...
   .start();
```

###### Reproduction Steps

1.
2.
3.

**Comment by javiersantos** [comment]
`.setCancelable(false)` with no buttons should work. Or use your own implementation by using AppUpdaterUtils: https://github.com/javiersantos/AppUpdater#using-custom-callbacks
