### ISSUE TITLE
Does not work. Nothing to see

### ISSUE THREAD

**Issue by Rupilein** [javiersantos/AppUpdater#117]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [X] I have verified that I am using the latest version of AppUpdater.
- [X] I have given my issue a non-generic title.
- [X] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
###### Builder
```Java
new AppUpdater(this)
   ...
   .start();
```

###### Reproduction Steps
I added this code to the onCreate function of my activity.

```Java
new AppUpdater(this)
	.setDisplay(com.github.javiersantos.appupdater.enums.Display.SNACKBAR)
	.setDuration(Duration.NORMAL)
	.setUpdateFrom(UpdateFrom.GOOGLE_PLAY)
	.showEvery(5)
	.start();
```

Then I made an update (beta). I installed the update. 
then I made another update. I can see the update in Google play store.
I open the app. But nothing to see. no snackbar. 
Does this work with beta versions of the app?
any advise? what I am doing wrong?

###### Expected Result
snackbar should show up

###### Actual Result
nothing shows up

**Comment by Rupilein** [comment]
ah ok. I found the answer in Wiki. doesn't seem to work with beta-versions.
But how can I test it?

**Comment by javiersantos** [comment]
You can't. The app and update must be visible on a browser to make the library work (beta versions are not showed).

**Comment by Rupilein** [comment]
I found a way to test. just put a lower version number in the manifest and start the app.
