### ISSUE TITLE
The JSON updater file is mal-formatted. AppUpdate can't check for updates

### ISSUE THREAD

**Issue by playSGK** [javiersantos/AppUpdater#118]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.x.x` (Doesn't used this)
 - Device OS version: `5.1`
 - Device Manufacturer: `Lenovo`
 - Device Name: `leneovo tab3 7Essentials`
 
###### Builder
```Java
AppUpdaterUtils appUpdaterUtils = new AppUpdaterUtils(getContext())
                .setUpdateFrom(UpdateFrom.JSON)
                .setUpdateJSON("https://somesite.com/MyApp/update-changelog.json")
                .withListener(new AppUpdaterUtils.UpdateListener() {
                    @Override
                    public void onSuccess(Update update, Boolean isUpdateAvailable) {
					Intent updateIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(update.getUrlToDownload().toString()));
                        updateIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                        getContext().startActivity(updateIntent);
					}
					
					@Override
                    public void onFailed(AppUpdaterError error) {
                        Log.d("AppUpdater Error", "Something went wrong");
                    }
                });
        appUpdaterUtils.start();
```

JSON I used

```Json
{
  "latestVersion": "1.0.1",
  "latestVersionCode": "2",
  "url": "https://somesite.com/app-debug.apk",
  "releaseNotes": [
    "- First evolution",
    "- Second evolution",
    "- Bug fixes"
  ]
}

```

###### Expected Result

Invoking Update Intent

###### Actual Result

The JSON updater file is mal-formatted. AppUpdate can't check for updates

**Comment by deepakkaku** [comment]
Even I am getting the same result. Any updates from anyone?

**Comment by javiersantos** [comment]
I'm looking into it.

**Comment by deepakkaku** [comment]
this format worked for me.
I don't see any difference to be honest

{
  "latestVersion": "1.2",
  "latestVersionCode": "2",
  "url": "http://www.google.com",
  "releaseNotes": ["v1.2","- New Scanner Scenario", "- Bug Fixes"]
}

**Comment by javiersantos** [comment]
I'm not able to reproduce the issue. I have tested using Android 5.1 & 8.1 and uploaded your JSON to Pastebin.

Does uploading the JSON to another server solve the problem?

**Comment by deepakkaku** [comment]
what happens when I set showEvery(5) and
How long does it wait to show the dialog again?

**Comment by William-Chow** [comment]
E/AppUpdater: The JSON updater file is mal-formatted. AppUpdate can't check for updates.

**Comment by javiersantos** [comment]
When `.showEvery(5)` is set, the dialog (snackbar or notification) will be displayed the first time that a new update has been found. Then it will only be displayed every 5 times that the builder has been called.
