### ISSUE TITLE
Missing resource?

### ISSUE THREAD

**Issue by KennyGoers** [javiersantos/AppUpdater#12]
When building and trying to include the 1.2 version I'm getting the following error:

Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

Thoughts?

**Comment by KennyGoers** [comment]
OK, false alarm, the compile directive needed a @aar and it built...

**Comment by javiersantos** [comment]
https://github.com/javiersantos/AppUpdater/commit/846be26fa679bcb1ff2cac7a0dfa7fd788d075af
