### ISSUE TITLE
OnClick Listeners Issue

### ISSUE THREAD

**Issue by mikemike396** [javiersantos/AppUpdater#121]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.6.4`
 - Device OS version: `8.0.0`
 - Device Manufacturer: `Simulator`
 - Device Name: `Nexus 5`
 
I am trying to use the OnClick listeners to log a few events in our analytics system. The issue is when I set the onClick listeners the library doesnt fire the library code. What I mean is if I click update it does nothing. Once I remove the onClickListeners it works fine. Am I missing something?

```
        final AppUpdater appUpdater = new AppUpdater(this)
                .setButtonDismissClickListener(new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        UpdateAppDialogEventLog updateAppDialogEventLog = new UpdateAppDialogEventLog();
                        updateAppDialogEventLog.didCancelUpdate = 1;
                        EventLoggingManager.logEventUpdateAppDidShowDialogWithSelection(updateAppDialogEventLog);
                    }
                })
                .setButtonDoNotShowAgainClickListener(new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        UpdateAppDialogEventLog updateAppDialogEventLog = new UpdateAppDialogEventLog();
                        updateAppDialogEventLog.didSkipAppVersion = 1;
                        EventLoggingManager.logEventUpdateAppDidShowDialogWithSelection(updateAppDialogEventLog);
                    }
                })
                .setButtonUpdateClickListener(new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int i) {
                        UpdateAppDialogEventLog updateAppDialogEventLog = new UpdateAppDialogEventLog();
                        updateAppDialogEventLog.didOpenAppStore = 1;
                        EventLoggingManager.logEventUpdateAppDidShowDialogWithSelection(updateAppDialogEventLog);
                    }
                })
                .setUpdateFrom(UpdateFrom.GOOGLE_PLAY);
        appUpdater.start();
```

**Comment by javiersantos** [comment]
Custom callbacks seems to be working properly. Keep in mind that when you use custom callbacks you will have to implements the actions manually (it will not launch the Intents automatically, for example).
