### ISSUE TITLE
It checks versionCode or versionName

### ISSUE THREAD

**Issue by hcrgithub** [javiersantos/AppUpdater#124]
Below is the scenario:
I had an app at playstore with below versionCode and versionName;
versionCode 1
versionName “1”

Now to test, I did below cases
Case 1:
versionCode 0
versionName "0.1"
Result : Update pop up **is displayed**

Case 2:
versionCode 1
versionName "1.1"
Result : Update pop up is **NOT displayed**

So does it compares with versionName? I just want to confirm it.

Thanks in advance,
Hooda

**Comment by javiersantos** [comment]
Google Play doesn't support versionCode. You should use UpdateFrom.JSON or UpdateFrom.XML instead.
