### ISSUE TITLE
Question : is this Lib can check alpha/beta publishes?

### ISSUE THREAD

**Issue by jc01rho** [javiersantos/AppUpdater#125]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
###### Builder
```Java
new AppUpdater(this)
   ...
   .start();
```

###### Reproduction Steps

1.
2.
3.

**Comment by javiersantos** [comment]
Duplicated #117 and explained in the [Wiki](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.GOOGLE_PLAY).

**Comment by jc01rho** [comment]
so sorry about inconvenience. my mistake :(
