### ISSUE TITLE
Force update and hide dismiss button

### ISSUE THREAD

**Issue by jigarfumakiya** [javiersantos/AppUpdater#144]
[x ] I have verified there are no duplicate active or recent bugs, questions, or requests.
[x ] I have verified that I am using the latest version of AppUpdater.
[x ] I have given my issue a non-generic title.
[x ] I have read over the README, Wiki and FAQs (before asking questions on how to do something).

How to Hide Button.
Particular how to force user to download new Version (How to hide dismiss button )

Thanks!!

**Comment by javiersantos** [comment]
There are already some issues on this topic. Try using `.setCancelable(false)` and `.setButtonDismiss("")`.
