### ISSUE TITLE
How to start automaticly download for update

### ISSUE THREAD

**Issue by UMUTBAYGUT** [javiersantos/AppUpdater#145]
Hello ,

  Hello in the listener how we can start automaticly update (download and install) ? 

public void onSuccess(Update update, Boolean isUpdateAvailable) {
        //in here
        }

**Comment by javiersantos** [comment]
This library doesn't provide a way to download and install the update (it's not allowed by Google Play Store). You must implement it on your own using DownloadManager or similar.
