### ISSUE TITLE
Warning : string 'app_name' marked untranslatable but exists in locale 'fr'

### ISSUE THREAD

**Issue by ahpiau18** [javiersantos/AppUpdater#15]
i'm getting warning while i build the project

**/Users/..../app/build/intermediates/res/merged/debug/values-fr/values-fr.xml**
**Warning:(22) warning: string 'app_name' marked untranslatable but exists in locale 'fr'**

Source:
"< string name="app_name" **translatable="false"** >AppUpdater< /string > "

**Comment by javiersantos** [comment]
Fixed in the latest update of the library (v1.2.1). Thanks!

```Javascript
dependencies {
    compile 'com.github.javiersantos:AppUpdater:1.2.1'
}
```
