### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by IAmNirmesh** [javiersantos/AppUpdater#153]
**Failed to resolve: com.github.javiersantos:AppUpdater:2.7**

I even have **maven { url "https://jitpack.io" }** in my Project gradle.

Please help @javiersantos

**Comment by IAmNirmesh** [comment]
Sorry @javiersantos . My silly mistake.
Closing the issue.

**Comment by jeniskasundra** [comment]
What is your silly mistake?
