### ISSUE TITLE
How to change strings colors?

### ISSUE THREAD

**Issue by welissonNeo** [javiersantos/AppUpdater#166]
In update from dialog, the texts colors are obtained from app default Accent Color. How to change library colors without changing Accent Color?

**Comment by javiersantos** [comment]
It isn't supported by the library. You should implement your own `AppUpdaterUtils` [implementation](https://github.com/javiersantos/AppUpdater#appupdaterutils) and display an AlertDialog with your custom style: https://stackoverflow.com/questions/16200914/alertdialog-styling-how-to-change-style-color-of-title-message-etc
