### ISSUE TITLE
AppUpdater appUpdater = new AppUpdater(this);
appUpdater.start();

### ISSUE THREAD

**Issue by big1990id** [javiersantos/AppUpdater#212]
<AppUpdater>
  <update>
    <latestVersion>1.2.2</latestVersion>
    <latestVersionCode>10</latestVersionCode>
    <url>https://github.com/javiersantos/AppUpdater/releases</url>
  </update>
</AppUpdater>

**Comment by big1990id** [comment]
> <AppUpdater>
>   <update>
>     <latestVersion>1.2.2</latestVersion>
>     <latestVersionCode>10</latestVersionCode>
>     <url>https://github.com/javiersantos/AppUpdater/releases</url>
>   </update>
> </AppUpdater>
>

**Comment by h0jeZvgoxFepBQ2C** [comment]
Maybe you should close all these incomplete issues @big1990id ?
