### ISSUE TITLE
How do i delete the .APK after i update my app ??

### ISSUE THREAD

**Issue by Nanumiric123** [javiersantos/AppUpdater#222]
- [ X] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [ X] I have verified that I am using the latest version of AppUpdater.
- [ X] I have given my issue a non-generic title.
- [X ] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
###### Builder
new AppUpdater(mContext)
                        .setUpdateFrom(UpdateFrom.JSON)
                        .setUpdateJSON("http://172.16.206.19/REST_API/json_format.json")
                        .setDisplay(Display.DIALOG)
                        .setCancelable(false) // Dialog could not be dismissable
                        .showAppUpdated(true)
                        .setButtonDoNotShowAgain(null)
                        .start();

How do i automatically clear the .apk file after i update my app  automatically ??

**Comment by Harisalimian2** [comment]
Update followers list

**Comment by javiersantos** [comment]
Downloading and installing APKs is not supported by the library.
