### ISSUE TITLE
Always get Latest Version 0.0.0.0 update from GOOGLE_PLAY 

### ISSUE THREAD

**Issue by IMWaqasFarooq** [javiersantos/AppUpdater#225]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `2.x.x`
 - Device OS version: `12`
 - Device Manufacturer: `Samsung`
 - Device Name: `GalaxyM31`
 
###### Builder
```
 AppUpdaterUtils appUpdaterUtils = new AppUpdaterUtils(this)
                .setUpdateFrom(UpdateFrom.GOOGLE_PLAY)
                .withListener(new AppUpdaterUtils.UpdateListener() {
                    @Override
                    public void onSuccess(Update update, Boolean isUpdateAvailable) {
                        Log.d("Latest Version ",  update.getLatestVersion());
                        Log.d("Release notes",  update.getReleaseNotes());
                        Log.d("URL",  update.getUrlToDownload().toString());
                        Log.d("Is update available? ", Boolean.toString(isUpdateAvailable));
                    }

                    @Override
                    public void onFailed(AppUpdaterError error) {
                        Log.d("AppUpdater Error", "Something went wrong");
                    }
                });
        appUpdaterUtils.start();
```

###### problem

Hi.. I want to ask, why I always get return Latest Version 0.0.0.0 while in the playstore has its version 1.2.0 . before this issue was appear earlier in 2018, now its appear again, and it was fixed as an temporary solution with update of 2.7, but current library version is still 2.7. so when this issue will resolve now 

###### Expected Result
Latest Version 6.2.0
Release notes
URL https://play.google.com/store/apps/details?id=com.city.tenantmnm&hl=en
Is update available?true

###### Actual Result

Latest Version 0.0.0
Release notes
URL https://play.google.com/store/apps/details?id=com.city.tenantmnm&hl=en
Is update available?false

**Comment by gmsirimanna** [comment]
any update on this? is this library still working? @IMWaqasFarooq @tdtran @matthewmayer @Neoklosch @vicktor

**Comment by javiersantos** [comment]
Google Play is currently not working due to changes on Google's side. I suggest you use another method like JSON: https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.JSON
