### ISSUE TITLE
About directly apk URL in xml file

### ISSUE THREAD

**Issue by ahmet-topal** [javiersantos/AppUpdater#228]
Hi, i want to use directly .apk link in xml file that:
<AppUpdate.r>
  <update.>

--->    "< url.>http.s://github.com/javiersantos/AppUpdater/releases</url"
  </update.>
</AppUpdater.>

like : "< url.>http.s://github.com/javiersantos/AppUpdater/releases/_**example.apk**_</url".>

Is that possible?

**Comment by javiersantos** [comment]
Yes, you can use the APK url in the XML. Please note that the library does not manage the download and installation of the file.
