### ISSUE TITLE
Version Number failed to Parse if contains Non-digits characters

### ISSUE THREAD

**Issue by khalifavi** [javiersantos/AppUpdater#24]
com.github.javiersantos.appupdater.objects.Version

The version object is using String of the project versionName, which could be anything including alphabet or symbols.

Version@compareTo(Version)

`int thisPart = i < thisParts.length ? Integer.parseInt(thisParts[i]) : 0;`

digit filter like in replaceAll could be added (ex.` replaceAll("[^0-9?!\\.]","")`)

**Comment by tevch** [comment]
Would be great
