### ISSUE TITLE
When Google Play is not a default App Store in Android

### ISSUE THREAD

**Issue by ahpiau18** [javiersantos/AppUpdater#26]
Having an issue, if user is using some "china-made" android phone, and Google Play is not the default App Store in the phone.

It will be great, if AppUpdater allow user to pass the apps URL into the "AppUpdaterUtils"

Thanks.

**Comment by pylerSM** [comment]
You can specify what to check
new AppUpdater(this)
    .setUpdateFrom(UpdateFrom.GITHUB)
    .setUpdateFrom(UpdateFrom.GOOGLE_PLAY)

**Comment by javiersantos** [comment]
The library supports [other App Stores](https://github.com/javiersantos/AppUpdater#providing-a-source-for-the-updates), such as GitHub, Aptoide, Amazon and F-Droid.

If your app is not available on the App Stores listed above you should use a custom XML file hosted in a server. A guide to implement a custom XML is available [at the wiki](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.XML).
