### ISSUE TITLE
Activity has leaked window...?

### ISSUE THREAD

**Issue by khaledkhj** [javiersantos/AppUpdater#31]
Hi,
I would like to thank you first for the good library,
and I am wondering if you can provide a function to cancel or hide he dialog if it's been shown!
becuse I am getting "Activity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView..." if I wanted to launch another activity and the dialog is being shown.

Thanks in advance.

**Comment by javiersantos** [comment]
The latest update allows to dismiss snackbars and dialogs: https://github.com/javiersantos/AppUpdater/commit/337f7d73e184ecfcbf9db33e15740ab37e732d69. Thank you for letting me know!

```Javascript
dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.2'
}
```

**Comment by khaledkhj** [comment]
Thanks a lot for the great work..
