### ISSUE TITLE
Unable to resolve host "sit30.ru": No address associated with hostname

### ISSUE THREAD

**Issue by garik888** [javiersantos/AppUpdater#37]
Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
android.os.AsyncTask$3.done (AsyncTask.java:309)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
java.util.concurrent.FutureTask.setException (FutureTask.java:223)
java.util.concurrent.FutureTask.run (FutureTask.java:242)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
arrow_drop_down
Caused by java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "sit30.ru": No address associated with hostname
com.github.javiersantos.appupdater.RssParser.parse (RssParser.java:33)
com.github.javiersantos.appupdater.UtilsLibrary.getLatestAppVersionXml (UtilsLibrary.java:201)
com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground (UtilsAsync.java:57)
com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground (UtilsAsync.java:13)
android.os.AsyncTask$2.call (AsyncTask.java:295)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
arrow_drop_down
Caused by java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "sit30.ru": No address associated with hostname
com.github.javiersantos.appupdater.RssParser.getInputStream (RssParser.java:41)
com.github.javiersantos.appupdater.RssParser.parse (RssParser.java:30)
com.github.javiersantos.appupdater.UtilsLibrary.getLatestAppVersionXml (UtilsLibrary.java:201)
com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground (UtilsAsync.java:57)
com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.doInBackground (UtilsAsync.java:13)
android.os.AsyncTask$2.call (AsyncTask.java:295)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)

**Comment by javiersantos** [comment]
Have you added the permissions in your `AndroidManifest.xml`?
```Java
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by garik888** [comment]
I have written all this!
I just did not have internet on your phone!

**Comment by garik888** [comment]
**javiersantos**, will be a decision in the near future?

**Comment by javiersantos** [comment]
I'm not able to reproduce this Exception (even when using the Airplane mode). Could you paste the builder that you are using so I can reproduce your issue?

**Comment by garik888** [comment]
Specify not from the existence of the domain sit30433.ru

**Comment by garik888** [comment]
Well, you got to call the error using fake web address?

**Comment by garik888** [comment]
???
