### ISSUE TITLE
XML link is down means

### ISSUE THREAD

**Issue by nithingowda** [javiersantos/AppUpdater#38]
XML link is down means app start to crash please fix

**Comment by nithingowda** [comment]
XML link is down, 404 or deleted in server means crashing

**Comment by javiersantos** [comment]
Could you provide me the XML link that you seems to be offline?

**Comment by nithingowda** [comment]
https://raw.githubusercontent.c@m/javiersantos/AppUpdater/master/app/update-changelog.xml

404 link

**Comment by javiersantos** [comment]
Oh, I understand. When the link is down the app crashes. I will take a look on it.

**Comment by nithingowda** [comment]
Thank you

**Comment by javiersantos** [comment]
The correct XML file link is `https://raw.githubusercontent.com/javiersantos/AppUpdater/master/app/update-changelog.xml`.

**Comment by nithingowda** [comment]
yes bro 
In Dropbox xml deleted means crashing
https://dl.dropboxusercontent.com/s/j0kczez430tq2iz/XML.xml

**Comment by nithingowda** [comment]
Blank xml is also not working bro
If Dropbox account disabled or bandwidth complected means apps get crashing because of xml
