### ISSUE TITLE
Check for updates in settings fragment

### ISSUE THREAD

**Issue by JackRoberts1998** [javiersantos/AppUpdater#39]
Hi whenever i try to implement Appupdater in the settings activity either as a menu option or a preference the app crashes is there anything i can do to fix it ?

**Comment by javiersantos** [comment]
I've updated the `app` project including an updater in Settings: https://github.com/javiersantos/AppUpdater/commit/6d41d69f7f92fcc2991fe02139497f9566cd173b

Hope it helps you.

**Comment by JackRoberts1998** [comment]
Thankyou very muchfor all your help i don't mean to cause trouble
