### ISSUE TITLE
Dialog options vertical

### ISSUE THREAD

**Issue by Spotik** [javiersantos/AppUpdater#41]
Hi there,

All buttons on dialog is showing in vertical. Is this a bug?

![9097b2d50ca848029cd5121c304f4506](https://cloud.githubusercontent.com/assets/4020471/17122736/629e8fee-52b4-11e6-9344-bcd98846b8ed.png)

**Comment by javiersantos** [comment]
No, it isn't. The buttons are shown in vertical because they don't have enough space to show horizontally.
