### ISSUE TITLE
Possiblity to use versionCode as well?

### ISSUE THREAD

**Issue by Thore1954** [javiersantos/AppUpdater#42]
Greetings and thanks for the great lib.
Sometimes developers (me for example) publish a new build of the application without changing the versionName and only increase the versionCode.
Is that possible to specify versionCode in the XML?
Also I was wondering why you doesn't use the more efficient and common JSON instead of XML?

**Comment by javiersantos** [comment]
https://github.com/javiersantos/AppUpdater/releases/tag/2.6
