### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by DanteAndroid** [javiersantos/AppUpdater#5]
Sorry, but I did not see any information about how does it get the latest version number?
Lately I want to add the Update function in my app, so a more specific document will be appreciated.

**Comment by javiersantos** [comment]
Basically it compares your app version with the latest version available in the `.setUpdateFrom(UpdateFrom)` that you have provided in the builder. A string with the version can be found in the page source, so the library retrieves this version (the latest one published) and checks if it's the installed one.

Hope it helps you.

**Comment by panadol007** [comment]
Hi javiersantos, I've following code kotlin project: 
`val appUpdater = AppUpdater(this)
                .setUpdateFrom(UpdateFrom.JSON)
                .setUpdateJSON(currentSystem.appUpdaterFullURI)
                .setButtonDoNotShowAgain("")    //Hide the 'Do not show again' button
                .showEvery(3)       // show every 3 times this code run
        appUpdater.start()`

And json object: 
`$data = [
                'latestVersion' => '1.0.1',
                "url" => "http://192.168.0.4:81/downloads/isms_nct_latest.apk",
    			"releaseNotes" => [
    			    "- First evolution",
    			    "- Second evolution",
    			    "- Bug fixes"
      			]
            ];`

The problem is... After we click to download and install the latest software, after 3 times restart the app, it pops up again to ask if want to update the app. 

The questions rise in... If appUpdater were to used, where and how shall we record the info 'oh hey, this device has already installed 1.0.1', if same json data receive again, don't pop up the dialog box.

**Comment by enwokoma** [comment]
Hey @panadol007 you should consider using a custom listener
```KOTLIN
val appUpdater = AppUpdater(this)
            .setUpdateFrom(UpdateFrom.JSON)
            .setUpdateJSON(currentSystem.appUpdaterFullURI)
            .withListener(new AppUpdaterUtils.UpdateListener() {
                    @Override
                    public void onSuccess(Update update, Boolean isUpdateAvailable) {
                       // Check Update
                          if (update.getLatestVersionCode() > BuildConfig.VERSION_CODE) {
                                  // Show Update Notice
                          } else {
                                  // No Update
                                 // TODO: Do something when no update
                           }
                    }

                    @Override
                    public void onFailed(AppUpdaterError appUpdaterError) {
                        
                    }
                });
    appUpdater.start()
