### ISSUE TITLE
Not Configured

### ISSUE THREAD

**Issue by abumoallim** [javiersantos/AppUpdater#52]
Cannot retrieve latest version. Is it configured properly?

**Comment by javiersantos** [comment]
Could you paste the URL of your app in the market and the constructor that you are using in your code?

In addition, is the library displaying an error message in the console?

**Comment by abumoallim** [comment]
Url of my App
https://play.google.com/store/apps/details?id=com.awqatesalah.awqaat_e_salaah&hl=en

i am using:
    new AppUpdater(MainActivity.this).setUpdateFrom(UpdateFrom.GOOGLE_PLAY).showEvery(5).start();

i am using it on MainActivity after toolbar on OnCreate:
  getWindow().requestFeature(Window.FEATURE_ACTION_BAR_OVERLAY);
        setContentView(R.layout.activity_main);
        toolbar = (Toolbar) findViewById(R.id.toolbar);
            setSupportActionBar(toolbar);
            getSupportActionBar().setTitle("Awqat-e-Salah");
        new AppUpdater(MainActivity.this).setUpdateFrom(UpdateFrom.GOOGLE_PLAY).showEvery(5).start();

No message in console

**Comment by javiersantos** [comment]
Your app may be using updates that varies by devices. Browse to the web version of the Play Store and see if the version details are displayed properly.

If not please use another source. I recommend you to use [JSON](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.JSON) or [XML](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.XML) where you will be able to configure the `versionCode` too.
