### ISSUE TITLE
how to hide don't show again button ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [javiersantos/AppUpdater#58]
i want to disable don't show again button in dialog in my app .

**Comment by msay2** [comment]
You can download the library and edit the setDialogButtonUpdate and setButtonUpdate including a DialogInterface.OnClickListener

**Comment by msay2** [comment]
This is not possible, but you can do it by changing the bookstore, if you need a guide I'm there

**Comment by georgethomas2015e** [comment]
This is possible just do it like this 
 appUpdater.setButtonDoNotShowAgain(null);

cheers :)

**Comment by msay2** [comment]
No, I do not think so

After I can not tell you because I can no longer use this library because it crash all my projects of applications.

**Comment by georgethomas2015e** [comment]
I have tried it in the same way as above, and its working fine in my application

**Comment by msay2** [comment]
I'm not sure Android Studio, but I use an IDE for Android smartphone.

The application is called AIDE this is Android studio for android.

My problem may come from that (but i'm not sure).

Otherwise, for your request I do not think it is possible

**Comment by georgethomas2015e** [comment]
yes i am working in android studio its all good in my app, i am using it like this

 AppUpdater appUpdater = new AppUpdater(this);
        appUpdater.setUpdateFrom(UpdateFrom.JSON);               appUpdater.setUpdateJSON("https://raw.githubusercontent.com/javiersantos/AppUpdater/master/app/update-changelog.json");
        appUpdater.setButtonDoNotShowAgain(null);
        appUpdater.start();

**Comment by msay2** [comment]
Oh, I was not aware that putting `appUpdater.setButtonDoNotShowAgain` to `null` could work

**Comment by georgethomas2015e** [comment]
**Add the repository to your project build.gradle:**

repositories {
    maven {
        url "https://jitpack.io"
    }
}
**And add the library to your module build.gradle:**

dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.5.1'
}

it should definitely work.....

**Comment by panadol007** [comment]
The version 'com.github.javiersantos:AppUpdater:2.6.5' doesn't support null value as per described: appUpdater.setButtonDoNotShowAgain(null);

However, appUpdater.setButtonDoNotShowAgain(""); does the trick.
