### ISSUE TITLE
Custom texts in library?

### ISSUE THREAD

**Issue by khrizt** [javiersantos/AppUpdater#6]
Hi,

I'm wondering if besides the appupdater_btn_disable and appupdater_btn_update there's a way to customize the message displayed to the user as I want to show it in the user's language.

Thanks

**Comment by javiersantos** [comment]
Check out the latest 1.2 update! Custom title, description and buttons are now supported.

```Java
// Customize the dialog title, description and buttons
.setDialogTitleWhenUpdateAvailable("Update available")
.setDialogDescriptionWhenUpdateAvailable("Check out the latest version available of my app!")
.setDialogButtonUpdate("Update now?")
.setDialogButtonDoNotShowAgain("Huh, not interested")
.setDialogTitleWhenUpdateNotAvailable("Update not available")
.setDialogDescriptionWhenUpdateNotAvailable("No update available. Check for updates again later!")
```

**Comment by khrizt** [comment]
Wow, perfect!!! Thanks a lot @javiersantos

**Comment by khrizt** [comment]
Just one thing, is it possible that the translation app_name marked as non-translatable is included in the french translation of the library? Gradle gave me a warning about that

**Comment by javiersantos** [comment]
Sure! Next update will solve the Gradle warning :+1:
