### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by msay2** [javiersantos/AppUpdater#61]
Hi, my application stops as soon as they are open while I have only added the library to my project, I do not even write the lines of codes.

**Comment by javiersantos** [comment]
Please, could you paste the log when the app crashes? 

Thank you.

**Comment by msay2** [comment]
I am not on computer but on Android smartphone, so the error report must be different from what you knew.

at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-14 07:53:47.950 6146 6146 E     AndroidRuntime                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-14 07:53:47.950 6146 6146 E     AndroidRuntime                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-14 07:53:47.950 6146 6146 E     AndroidRuntime                               ... 13 more
11-14 07:53:47.950 6146 6146 E     AndroidRuntime                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-14 07:53:50.513 6146 6146 I     Process                                      Sending signal. PID: 6146 SIG: 9
11-14 07:57:18.756 6685 6685 I     art                                          Late-enabling -Xcheck:jni
11-14 07:57:18.883 6685 6695 I     art                                          Background sticky concurrent mark sweep GC freed 2718(123KB) AllocSpace objects, 0(0B) LOS objects, 69% free, 389KB/1283KB, paused 9.002ms total 85.571ms
11-14 07:57:19.154 6685 6685 W     System                                       ClassLoader referenced unknown path: /data/app/com.msay2.lite.pexpe-2/lib/arm
11-14 07:57:19.369 6685 6685 W     art                                          Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
11-14 07:57:19.673 6685 6703 D     OpenGLRenderer                               Use EGL_SWAP_BEHAVIOR_PRESERVED: false
11-14 07:57:19.751 6685 6703 D     libEGL                                       loaded /system/lib/egl/libEGL_mali.so
11-14 07:57:19.774 6685 6703 D     libEGL                                       loaded /system/lib/egl/libGLESv1_CM_mali.so
11-14 07:57:19.832 6685 6703 D     libEGL                                       loaded /system/lib/egl/libGLESv2_mali.so
11-14 07:57:19.909 6685 6703 I     OpenGLRenderer                               Initialized EGL, version 1.4
11-14 07:57:20.726 6685 6685 D     AndroidRuntime                               Shutting down VM
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               FATAL EXCEPTION: main
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               Process: com.msay2.lite.pexpe, PID: 6685
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               Theme: themes:{}
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               java.lang.NoClassDefFoundError: Failed resolution of: Lren/qinc/edit/PerformEdit;
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at com.msay2.lite.pexpe.pmTextEdit.<clinit>(pmTextEdit.java)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at java.lang.Class.classForName(Native Method)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at java.lang.Class.forName(Class.java:324)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at java.lang.Class.forName(Class.java:285)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at com.msay2.lite.pexpe.SplashScreen$100000000.run(SplashScreen.java:32)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at android.os.Handler.handleCallback(Handler.java:739)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at android.os.Looper.loop(Looper.java:148)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:5463)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at java.lang.reflect.Method.invoke(Native Method)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               Caused by: java.lang.ClassNotFoundException: Didn't find class "ren.qinc.edit.PerformEdit" on path: DexPathList[[zip file "/data/app/com.msay2.lite.pexpe-2/base.apk"],nativeLibraryDirectories=[/data/app/com.msay2.lite.pexpe-2/lib/arm, /vendor/lib, /system/lib, /system/lib/ste_omxcomponents]]
11-14 07:57:20.779 6685 6685 E     AndroidRuntime                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

A line still caught my attention: 

Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Is it because of that?

**Comment by javiersantos** [comment]
I think it is not related with the library, seems to be something wrong with your `AndroidManifest.xml`. Have you included the `PerformEdit` activity into your `AndroidManifest.xml`?

This [stackoverflow post](http://stackoverflow.com/questions/20924004/android-classnotfoundexception-didnt-find-class-on-path) could help you.

**Comment by msay2** [comment]
`PerformEdit` is not an `Activity` but a library. But I still looked at what you mentioned about `PerformEdit`. The `PerformEdit` is a library from Github this library allows me to add the undo and redo function to my edittext but I realized that the import was faulty (why ... I do not know) so I copied the java file of this Bookstore and I pasted it into my project and there ... no crash, so ultimately it was `PerformEdit` that was faulty. Merci beaucoup

**Comment by javiersantos** [comment]
No problem! Nice to know that it is working now.

**Comment by msay2** [comment]
Hi, now that the error has been fixed I get a new obstacle.

I can no longer browse my other activities (which are well written in the AndroidManifest.xml)

And this is where I no longer understand anything ... because as soon as I remove your bookstore the obstacle disappears, but as soon as I put your bookstore in my project these errors occur. Despite that your bookstore works very well 

```java.lang.NoClassDefFoundError: com.msay2.lite.pexpe.BottomSheetApPref$100000001
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at com.msay2.lite.pexpe.BottomSheetApPref.<init>(BottomSheetApPref.java:80)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at java.lang.Class.newInstance(Native Method)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.os.Looper.loop(Looper.java:148)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:5463)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at java.lang.reflect.Method.invoke(Native Method)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-16 12:04:22.702 19656 19656 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)```

**Comment by msay2** [comment]
Sorry to go back on this closed topic, but I would have a simple question to ask you ... have you already use your library with the `Palette-v7.25.0.0` ?
