### ISSUE TITLE
error LatestAppVersion.onPostExecute

### ISSUE THREAD

**Issue by SGAXEU** [javiersantos/AppUpdater#64]
Good some of my users are giving the following error in devices with Android OS: 4.4.2.
I attach the trace

android.view.ViewRootImpl.setView (ViewRootImpl.java:727)
android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:278)
android.view.WindowManagerImpl.addView (WindowManagerImpl.java:69)
android.app.Dialog.show (Dialog.java:288)
com.github.javiersantos.appupdater.AppUpdater$1.onSuccess (AppUpdater.java:302)
com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.onPostExecute (UtilsAsync.java:74)
com.github.javiersantos.appupdater.UtilsAsync$LatestAppVersion.onPostExecute (UtilsAsync.java:13)
android.os.AsyncTask.finish (AsyncTask.java:632)
android.os.AsyncTask.access$600 (AsyncTask.java:177)
android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:645)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:157)
android.app.ActivityThread.main (ActivityThread.java:5293)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1265)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1081)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by javiersantos** [comment]
Could you please update to the latest update? Thank you.

```Javascript
dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.5.1'
}
```
