### ISSUE TITLE
LibraryListener object not null in PreExecute but null in PostExecute - listener not called

### ISSUE THREAD

**Issue by pirocso** [javiersantos/AppUpdater#69]
LibraryListener listener = (LibraryListener)this.listenerRef.get()

The above line in the LatestAppVersion::PreExecute method works fine and returns the LibraryListener created in AppUpdater::start but returns null in LatestAppVersion::PostExecute

Running on 2nd gen Moto E with Android 6.0

I am calling AppUpdater in my main activity's onCreate with _new AppUpdater(this).start();_

**Comment by mememto** [comment]
same problem for me :/

**Comment by pratikpopat** [comment]
Same problem :(

**Comment by javiersantos** [comment]
https://github.com/javiersantos/AppUpdater/releases/tag/2.5.3
