### ISSUE TITLE
I do not receive any type of notification

### ISSUE THREAD

**Issue by EminDemiri** [javiersantos/AppUpdater#79]
I'm trying to display a notification for the presence of an update on playstore but I do not receive anything, I have no error between the logs.

this is my app: https://play.google.com/store/apps/details?id=com.movisystem.flippycard

and this is the code I use in a fragment
`new AppUpdater(getActivity())
                    .setDisplay(Display.NOTIFICATION)
                    .setUpdateFrom(UpdateFrom.GOOGLE_PLAY)
                    .showAppUpdated(false)
                    .start();`

can you help me?

**Comment by javiersantos** [comment]
https://github.com/javiersantos/AppUpdater/releases/tag/2.5.3

**Comment by lucasbusellato** [comment]
I'm targeting API 27 and I'm not receiving notifications.
After checking the logs, I've found this error:

`NotificationService: No Channel found for pkg=my.package, channelId=null, id=0, tag=null, opPkg=my.package, callingUid=10322, userId=0, incomingUserId=0, notificationUid=10322, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=content://settings/system/notification_sound defaults=0x0 flags=0x18 color=0x00000000 actions=1 vis=PRIVATE)`

If I understood correctly, now the channel ID is [required](https://stackoverflow.com/a/45692202).

**Comment by javiersantos** [comment]
https://github.com/javiersantos/AppUpdater/releases/tag/2.6.5

**Comment by lucasbusellato** [comment]
@javiersantos Perfect! It's working now.

Thank you for the quick response and this awesome lib.
