### ISSUE TITLE
Error:(130, 13) Failed to resolve: com.github.javiersantos:AppUpdater:2.5.4

### ISSUE THREAD

**Issue by yofu1234** [javiersantos/AppUpdater#81]
Error:(130, 13) Failed to resolve: com.github.javiersantos:AppUpdater:2.5.4

I can import other libraries but for some reason, I can't import this library.

**Comment by javiersantos** [comment]
Have you added the Jitpack repository to your project build.gradle?

```repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}```

https://github.com/javiersantos/AppUpdater/blob/master/build.gradle

**Comment by yofu1234** [comment]
My bad, I had thought I already added it with my previous libraries but I didn't. Problem solved.
