### ISSUE TITLE
Is there anyway to get rid of these default words on the dialog and replace them with my JSON. Right now, JSON only adds words, not replace them.

### ISSUE THREAD

**Issue by yofu1234** [javiersantos/AppUpdater#82]
Is there anyway to get rid of these default words on the dialog and replace them with my JSON. Right now, JSON only adds words, not replace the two lines.

![screen shot 2017-03-29 at 3 18 31 pm](https://cloud.githubusercontent.com/assets/12259153/24472347/615bc13c-1493-11e7-8693-8f3b525e08da.png)

Here is my json: https://github.com/yofu1234/androidappupdate/blob/master/update-changelog.json

**Comment by javiersantos** [comment]
After next update, you should use `.setContentOnUpdateAvailable("")` to display only the release notes.

If you need this change as soon as possible you can get this change by using the commit as the library version.

```gradle
dependencies {
    compile 'com.github.javiersantos:AppUpdater:0fa15043e8'
}
```

**Comment by javiersantos** [comment]
https://github.com/javiersantos/AppUpdater/releases/tag/2.6
