### ISSUE TITLE
Dialog don't pop up when including latestVersionCode (JSON)

### ISSUE THREAD

**Issue by yofu1234** [javiersantos/AppUpdater#85]
In the new 2.6 version:

```
{
  "latestVersion": "1.2.2",
  "latestVersionCode": 10,
  "url": "https://github.com/javiersantos/AppUpdater/releases",
  "releaseNotes": [
    "- First evolution",
    "- Second evolution",
    "- Bug fixes"
  ]
}
```

If you don't include `latestVersionCode` in your JSON, the update dialog won't pop up.

**Comment by javiersantos** [comment]
Update 2.6.1 should fix this issue: https://github.com/javiersantos/AppUpdater/releases/tag/2.6.1

**Comment by yofu1234** [comment]
Ok, this is weird. After the latest update the dialog just doesn't show up at all:
https://github.com/yofu1234/androidappupdate/blob/master/update-changelog.json

**Comment by javiersantos** [comment]
Your JSON is mal-formatted. If you see the Android log there is a message like this:

`E/AppUpdater: The JSON updater file is mal-formatted. AppUpdate can't check for updates.`

You need to remove the comma (`,`) of the latest `releaseNotes` item.

Your JSON:

```json

{
  "latestVersion": "2.17",
      "latestVersionCode": 47,
  "url": "https://play.google.com/store/apps/details?id=com.stackkedteam.feedshare",
  "releaseNotes": [
    "1. Added GOING button. Hit GOING to tell the poster you are going & get notified whenever someone comments on the post",
  ]
}
```

The correct one:

```json
{
  "latestVersion": "2.17",
      "latestVersionCode": 47,
  "url": "https://play.google.com/store/apps/details?id=com.stackkedteam.feedshare",
  "releaseNotes": [
    "1. Added GOING button. Hit GOING to tell the poster you are going & get notified whenever someone comments on the post"
  ]
}
```

**Comment by yofu1234** [comment]
Thanks, works now!
