### ISSUE TITLE
can not restrict users to show dialog while users click outside dialog.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [javiersantos/AppUpdater#88]
there is no method to restrict dialog to go hide while user click outside of dialog. i do not want to hide dialog when any user click outside of dialog.

**Comment by erionialb** [comment]
on UtilsDisplay.java use this method : 

.setPositiveButton(btnPositive, updateClickListener).setCancelable(false).show();

**Comment by javiersantos** [comment]
The method `.setCancelable(boolean)` has been added to AppUpdater v2.6.2 to make the dialog dismissable. 

```Gradle
dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.6.2'
}
```
