### ISSUE TITLE
Unable to get "No updates available dialog"

### ISSUE THREAD

**Issue by ujwalp15** [javiersantos/AppUpdater#89]
This is my current setup
new AppUpdater(this)
                    .setUpdateFrom(UpdateFrom.JSON)
                    .setUpdateJSON("https://raw.githubusercontent.com/Bella-Assistant/Bella-Android/master/update-changelog.json")
                    .setTitleOnUpdateNotAvailable("Update not available")
                    .setContentOnUpdateNotAvailable("No update available. Check for updates again later!")
                    .setDisplay(com.github.javiersantos.appupdater.enums.Display.DIALOG)
                    .start();

My App versionname and code are 1.11 and 10 and the same is put up in the json, So technically, when I check for update I am supposed to get a dialog saying "No update available" but I am not getting any dialog.

**Comment by pye52** [comment]
call`showAppUpdated(true)`before`start()`
then u will see the dialog
