### ISSUE TITLE
build.gradle dependency error

### ISSUE THREAD

**Issue by ciammarica** [javiersantos/AppUpdater#91]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md) and [WIKI](https://github.com/javiersantos/AppUpdater/wiki) (before asking questions on how to do something).

###### Details
 - AppUpdater version: `2.6.1`
 - Android Studio version: `2.3.2`
 - Gradle version: `3.3`
 - Android plugin version: `2.3.2`

###### Reproduction Steps

1. Add the repository to your project build.gradle:

```gradle
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```

2. Add the library to your module build.gradle:

```gradle
dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.6.1'
}
```
 
3. Sync project

###### Expected Result

Project build with no errors.

###### Actual Result

Error message: "Failed to resolve: com.github.javiersantos:AppUpdater:2.6.1"

**Comment by hpng6** [comment]
same problem to me also.

**Comment by IAmEska** [comment]
Hello,
I guess you did put repository definition inside buildscript in your build.gradle.
Check that you have your jitpack repository definition outside of buildscript.
It´s working for me.

**wrong:**
buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
    }
 }

**ok:**
repositories {
    maven { url 'https://jitpack.io' }
}

**Comment by javiersantos** [comment]
As @IAmEska says, the Jitpack repository should be placed outside of buildscript. Please follow this example.

```gradle
apply plugin: 'com.android.application'

android {
    ....
}

repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    ...
    compile 'com.github.javiersantos:AppUpdater:[LATEST_VERSION]'
}

**Comment by MohammadNazarian** [comment]
Hello,
No:
```
buildscript {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```
Yes:
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```
