### ISSUE TITLE
Separate Update and No Update notification

### ISSUE THREAD

**Issue by Berlon** [javiersantos/AppUpdater#92]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

Thanks for the great lib. I was wondering is there a way to separate the Update and No Update portion of the code? I would like to change the No Update notification to a snack bar and leave the Update notification as a dialog. Or just stop the No Update notification.

**Comment by javiersantos** [comment]
It is not possible when using the `AppUpdater` builder, but you can use the [`AppUpdaterUtils` builder instead](https://github.com/javiersantos/AppUpdater#using-custom-callbacks) and show a dialog or snackbar based on the results. For example:

```Java
AppUpdaterUtils appUpdaterUtils = new AppUpdaterUtils(this)
    //.setUpdateFrom(UpdateFrom.AMAZON)
    //.setUpdateFrom(UpdateFrom.GITHUB)
    //.setGitHubUserAndRepo("javiersantos", "AppUpdater")
    //...
    .withListener(new AppUpdaterUtils.UpdateListener() {
        @Override
        public void onSuccess(Update update, Boolean isUpdateAvailable) {
           if (isUpdateAvailable) {
              // Show a Dialog
           } else {
              // Show a Snackbar
           }
        }
        
        @Override
        public void onFailed(AppUpdaterError error) {
            Log.d("AppUpdater Error", "Something went wrong");
        }
     });
appUpdaterUtils.start();
```
