### ISSUE TITLE
Never new version

### ISSUE THREAD

**Issue by EnzChe** [javiersantos/AppUpdater#97]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of AppUpdater.
- [x] I have given my issue a non-generic title.
- [x] I have read over the [README](https://github.com/javiersantos/AppUpdater/blob/master/README.md), [Wiki](https://github.com/javiersantos/AppUpdater/wiki) and [FAQs](https://github.com/javiersantos/AppUpdater/wiki/FAQs) (before asking questions on how to do something).

###### Details
 - AppUpdater version: `2.6.1`
 - Device OS version: `5.1`
 - Device Name: `Emulator API 24`

###### Actual Code

```
// Auto Updater
        AppUpdaterUtils appUpdater = new AppUpdaterUtils(this)
                .setUpdateFrom(UpdateFrom.JSON)
                .setUpdateJSON(getResources().getString(R.string.config_update_link))
                .withListener(new AppUpdaterUtils.UpdateListener() {
                    @Override
                    public void onSuccess(Update update, Boolean isUpdateAvailable) {
                        if (isUpdateAvailable) {
                            Log.d("__________", "1 - It's working");
                        } else {
                            Log.d("__________", "2 - It's nearly working");
                        }
                    }

                    @Override
                    public void onFailed(AppUpdaterError error) {
                        Log.d("AppUpdater Error", "Something went wrong" + error);
                    }
                });
        appUpdater.start();
```
```
{
latestVersion: "0.0.3",
latestVersionCode: "1",
url: "http://***.***.com/api/download-apk",
releaseNotes: [
"Ajout du droit d'écriture dans dossier APK backoffice"
]
}
```

###### Expected Result
It's nearly working on Logs.

###### Actual Result
The application never detect new versions, when I call 'update.getLatestVersion()' the latest version is 0.0.3 (the real latest version on my server), and when I go in device, App properties the App version is 0.0.1. So why the 'isUpdateAvailable' is false ?

**Comment by EnzChe** [comment]
Ok I got it. I am actually using com.toptoche.searchablespinnerlibrary.

And this library got a BuildConfig class containing VERSION_NAME = "1.3.1";
My app was installed at 0.0.1 and for testing I tested with 0.0.2 & 0.0.3.

Seems like AppUpdater was taking the current version of app installed is "1.3.1" and not "0.0.1". Because when I upload the new version on server over than 1.3.1+, then the listener is correctly working.

**Comment by javiersantos** [comment]
I think your issue is related with this, as explained in the [WIKI](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.JSON).
> If `latestVersionCode` is included in the JSON, `latestVersion` will only be used to display the latest version in the dialog and the `versionCode` will be used to compare the installed and latest update.

Do increasing the `versionCode` solve your issue?
