### ISSUE TITLE
Not getting App Update , Getting below code when debug the code.

### ISSUE THREAD

**Issue by Raja2141** [javiersantos/AppUpdater#98]
We are getting below error when debug the apk  "<!DOCTYPE html><html><head><meta http-equiv="content-type" content="text/html;charset=utf-8"><link rel="shortcut icon" href="//www.gstatic.com/android/market_images/web/favicon_v2.ico"><title>Not Found</title>"

**Comment by javiersantos** [comment]
Please follow the template when posting an issue. There is no way to reproduce your issue with these details.

**Comment by Raja2141** [comment]
## Not Found
> We are getting below error when debug the apk:
[test.txt](https://github.com/javiersantos/AppUpdater/files/1255235/test.txt)

**Comment by javiersantos** [comment]
Something is wrong with your configuration.

Have a look at the wiki for more info: [UpdateFrom.XML](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.XML) or [UpdateFrom.JSON](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.JSON).
