### ISSUE TITLE
LatestVersionCode is always null

### ISSUE THREAD

**Issue by SembaMax** [javiersantos/AppUpdater#99]
AppUpdaterUtils appUpdaterUtils = new AppUpdaterUtils(this)
    .setUpdateFrom(UpdateFrom.GOOGLE_PLAY)
    .withListener(new AppUpdaterUtils.UpdateListener() {
        @Override
        public void onSuccess(Update update, Boolean isUpdateAvailable) {
	    Log.d("Latest Version Code", update.**getLatestVersionCode**()); 
        }
        
        @Override
        public void onFailed(AppUpdaterError error) {
            Log.d("AppUpdater Error", "Something went wrong");
        }
     });
appUpdaterUtils.start();
---------------------------------------------------------------------------------------
I used that code mentioned above and it worked fine.
but the latest version code always has a null value.

**Comment by javiersantos** [comment]
`Update#getLatestVersionCode()` is only available when using [UpdateFrom.JSON](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.JSON) or [UpdateFrom.XML](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.XML). You should use `Update#getLatestVersion()` instead.
